[package]
name = "hotelplus_odoo_sentinel"
version = "0.1.0"
edition = "2021"

[dependencies]
json = "0.12.4"
reqwest = { version = "0.12.12", features = ["json"] }
futures = "0.3"
tokio = { version = "1.43.0", features = ["full"]}
mysql = "26.0.0"
